apiVersion: v1
data:
  name: {{cookiecutter.project_slug}}
  project: default
  type: repo
  url: https://github.com/{{cookiecutter.github_username}}/app-{{cookiecutter.prokect_slug}}.git
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-{{cookiecutter.project_slug}}
  namespace: argocd
type: Opaque
