apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{cookiecutter.project_slug}}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/{{cookiecutter.github_username}}/app-{{cookiecutter.project_slug}}.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: {{cookiecutter.project_slug}}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
