apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: react-template
  title: React Template
  description: A React template that creates a basic React app with Cookiecutter
spec:
  owner: user:guest
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Let's React to something
      required:
        - project_name
        - github_username
      properties:
        project_name:
          title: Name
          type: string
          description: Unique name of the app
          ui:autofocus: true
          ui:options:
            rows: 5
        github_username:
          title: Github Username
          type: string
          description: Your github username
          ui:autofocus: true
          ui:options:
            rows: 5

  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  steps:
    # Each step executes an action, in this case one templates files into the working directory.
    - id: fetch-base
      name: Fetch Base
      action: fetch:cookiecutter
      input:
        url: ./content
        values:
          project_name: ${{ parameters.project_name }}
          github_username: ${{ parameters.github_username }}

    # This step publishes the contents of the working directory to GitHub.
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.project_name }}
        repoUrl: github.com?repo=app-${{ parameters.project_name|replace(" ", "-")|replace("_", "-")|replace(".", "-")|lower|trim }}&owner=${{ parameters.github_username }}
        sourcePath: ./app-${{ parameters.project_name|replace(" ", "-")|replace("_", "-")|replace(".", "-")|lower|trim }}
        defaultBranch: main

    # The final step is to register our new component in the catalog.
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
        optional: true

    - id: app
      name: ArgoCD App
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=my-backstage&owner=${{ parameters.github_username }}
        branchName: argocd-app-${{ parameters.project_name|replace(" ", "-")|replace("_", "-")|replace(".", "-")|lower|trim }}
        targetBranchName: main
        title: Add ArgoCD App for ${{ parameters.project_name }}
        description: |
          This PR adds an ArgoCD App for ${{ parameters.project_name }}.
          It will deploy the app to the `argocd` namespace.
        commitMessage: Add ArgoCD App for ${{ parameters.project_name }}
        sourcePath: ./manifests/
        targetPath: ./manifests/
      output:
        remoteUrl: ${{ steps['app'].output.remoteUrl }}



  # Outputs are displayed to the user after a successful execution of the template.
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
