{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "backstage-secrets",
    "namespace": "backstage",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "backstage-secrets",
        "namespace": "backstage",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "GITHUB_TOKEN": "AgA9kbqukMNT/BW5S/gDJt9cOGY3cloVq+uM6zWIoMrwM2e3nzxlFqD7n1gbSL0kCezsj5jbDrspjPihKYJWKlJcdrLiIyI3zFG9VOUvMaJJ/Z4EnrBzL60yJ1twiPmC9QCjfokUEH7yAwOzNEsSqB0qqD91fgp8qnHBF2/iPF4JVR43oyRybfhNXMA6mwC6T8cjIOJlXMBQ0s3aFfP1bUgGD6HcHngZi1Kvq8+Tr6WWcytKy6xJajJd3PGEUJy+qWU4xaOl6b7uM2sL0shTrnkfvfM7k5f7CStMVaQVA9RpFiidv8ijIK+L56XQFAxY8NAIgW5vmyYGljOPi3otr9twSYRFFBO+1qYe9rW9nDjb1CWjBe6n6baagAY8/DCgeI1VtTco/J0gHv4zxadpg6/+nk9Ij8T41gDbf1fdQUF3ZyPbFwVVvD8n1FPmlk/czhs8N0CVWDvQ9Om/8Zax9UQMuIGoOtki4w6r+KC9e1bmCauZe9t1DdcNtpwfJvHGd/Pv7ytFSF7GUmCYfjOzNC/EJawIdohe8eFN0hloJNw7GXYkrBWrqb4hMhAX+D1/LGN80NjsVVXC5R8RBrzvLyjjFxSO++O9RfMnrpw7BVzdsu9ZY6axDH+O9HK4wTtAMRRaYZYBdaNUml2SzKcjj2/3CdDlOfiY1oui6OKffgT3PZDy/t5TaajjFg5hyHgPuSGZLPe5GBn+GqkVPPIdPgrFR8FYlcMdxc+Oee0nMNKawxrTOhJ1Ut6iEQ=="
    }
  }
}
