{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "postgres-secrets",
    "namespace": "backstage",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "postgres-secrets",
        "namespace": "backstage",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "POSTGRES_PASSWORD": "AgA7UsXJyIVxaeynexb4ihTOZ2EmiL/1zo5nPxumHEucS6E2ruPRvUeW9gXCHgFWBtTMUjH+feAr3AcTvoxvAF0HCiJ7UtH0dX5t9UnNAuW3u7vvTD9kDm0usoRcflzOG5/GzlmvOF+cS2WsHDIS+qB1ylMrSaqc3vliVuJLoAMH6NQRDsKZj0IZhEsjgv8y3PRvC/exIea3umphheqgjTJdtaxKixf2CW3M1W4jG/34GMFa4bXPXyQTdg1oovwIVorM/2BituqzscNgZKqRHEFRz2RlmhkhbEL8ETFnk2tpo+sZHmuisLWpFGfNXG8NcdRq0WP6nC7fv4RRfyyap0N/6q8wRCA9TWlVFbF3yliwicdZf6+IEc1el4sK8eA23wMkKgVZinoowHiNF4N9YOgzbx3l4T37vG5SvsFGuUhjdmG/603w9w0G6otcJ2nsp8wCxrGWuFZNGVblrzYzSPx6r3P1LSndhL6/aq74wnLNZ6jW/FcpmF4dPBk7R0LMZZ+V0s8m2biZOPtZMNhaJh6GM8OPjMHLoyHCMCARgm1S54QwoCeUTybmZGqtrN8D413lY9t91y1uKNwgeiFPKbxptyUnZNrSZ5mtGSPQsblBy+qIt5EmHmKn+h/V0cgyrOP+VgjE33kuJ1lF5A+8bFJ4wyja7rE3ieenAMyIp3gtJCdlBxYlvxUjK7Mi361WU12aHPy9jcw6",
      "POSTGRES_USER": "AgBoxpWk2zuoSXTjIfL+d+NULmsMk+IKmIMEkOP4AVGQdrMvvBFx42skudfqKcSBkcdQt7BH6KYiDIAwGlUnDR0s5TkgCStJpsYayv0ZinhuMPsZ0V7u0ARD7tMrUuQaJ2Q2zBkgryX9My0+TEEWRF5jZNA8rxmFQOw7FfqZHq1rcplISorOYeh2yYvFrPp2oqRYQTdtg78dd3lud2KfuLSeKdmqgAL/pPgKO2dhpWFouMhBinr/r1JNMeDOJVuKfSzxA8Uwm8VldjdyOKklxp+X5yD945CBcJPRO1LanyeO4MEbo5+/YInZUp0kVDNRPv5Li7yw77U+Lr9aPnnKO8pDpRo0mZUxqbTJMwP735VOaueaed3NyOV6lgLZUmFVo2JEDdiAQpz/CwUzsKEvIHc10PBbAwSi94Y9BO0d4GexjDdpYwKlCJDxlNJkUz/3FdHIYv1vwEnuxJzpGqMOnWhUkNTAzmgTUPwkQ50A3stXTiSKYfbmrxwMTrVZpKZkEFhRlOoRaeXi8xBQQGTVbWLOTkIzMGhvOW5mbJOui/tEwK6HHz8zNhEoO0JbBs9ey+mX1h2d52RwZL1ktwR4TnfjbmuzIGy4BouY92+FEk9yVUeacGiRT6x+G8SW5VJu0YIHV3McJps6GuFXJqsm/dHGN16wVEz78UGXSgmkcrrMiT1Dmdr+akk19XTuvkyya2aT8S/G8xd7ghM="
    }
  }
}
