{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "postgres-secrets",
    "namespace": "backstage",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "postgres-secrets",
        "namespace": "backstage",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "POSTGRES_PASSWORD": "AgAY/oZVco2USZ52CMcxQLxXsqOhIFreEKgaFabfl9+uXgoqerirOkf2RGtouolFa4h+/s3zboH7VilUUzgu5gMQedgNOkaDlWWsNC/ciQmk8sI/9dqALaqN8QZRNxm20LawMmRho4cUKzADqrGJRCJSU6AuMgRxsNRdhfMHvxeo/0sP4a/sgAbi8WCHedDnmWbV0bQ0bTpr/0a0eH7GZ1lfenv/fjiFUzKpwRyP6BAHwTuN6KltuuKcaYYz/LiqOjIlgZVfFUp4HQ0aT7QlkOKzkch9NV8gZ4xm1+0Wsgd4LbDIDHCm2X+EmxFEahnrA88STNVobqUWuj4iOCpY/ylNgFvtIABoKP0BK0HaWMKmwC+z9ME0RLer/mNVyY3qYKHUZL/WYLnXqnqKTJrVYxbmiY/W2CfTJHuhLheM059BuNEbrAII7oWnRnMVXymtJIxAtMhasoVe/zo43d3inRZUmyE5TLV6hDgB7k61FduC0JBFJFZLsqdhD4Uo9fkplQ3Ah+kuh8yWAWf5ccZGFkOUpmqwTngleWBIt8OqAf/3bPDbWE7SK6akOyA7FMHEB0JFvaE9JJTsYb1O6uihjsGjVm2aZ8bDFG7Zma6HmuPFJRmK28VfVFuXt7/YBuGLfrgFTLJWscu3Wp/mvIClODusQK5KSgwLPiVUQ6jeiAAvOUFTbMFYBI8ThpJSncRMLcMBHVAFsO5xPQw=",
      "POSTGRES_USER": "AgA0PU/XSPPjWaHF4Okv5KmGn71xMCkC9zq/mX+g1ePVUuxuJssHyCIV2tuXBPZPPcTAGs3Seoptav30kxMxAYa1hqikUm+dTCC6oX0gKBIU1tgugcllEZb+lb3j1P+ugASAxsaOUlnrauQZFVoS/Wp4UZJcqWNOBcTjOI7M1H9xqVtDdjiqVRDyA23F4csGXEVciXWrDuz2bmULcBbMHCNPwK7fz09msl5c3maBZbytYwo/KzMD0jvL3i5ET/b9LbkVTbO+/QTWzZh9G5W9feLyg0Yu6ksyX/ZNu32O1bltz7ixibj2i7MHF2O3veKPNwgRIWjcTRxNiGHtKgsD9vWyToz8w+kyI5sPDUo9WcZ/zkhGBkuJ8u9qsIltUQ4TohGomcIi4OBIx0iqLf/dWtuFTxRozoyqwePviDLE6DnZzvaYwKkF63Z6xxBR248aa++PtOjXx6JMEWTRzSUtzY8ZQuZZotQIZfCAXpRa2DFUwVz5dtVSppdnkSl26Vl5C4QdLT184KxJ0PeSM8OtGMfcCXfuFXPQZ69e3WIIb34eD7Xc0yjFw7pGmHNAXGzwkzmzaQloDz4huYnSrekp7DcnU9dCZx3AXQTt90D3f2MPh47hIhotVGxZD28I3PKnhvuvWloxVUYoIr8RiHHcb8LQ1diHFIrfPHY4Saq7iGY0jQNJJcClwizrfsTbwsPvcKOPTTgSOM+GMjA="
    }
  }
}
