{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "postgres-secrets",
    "namespace": "backstage",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "postgres-secrets",
        "namespace": "backstage",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "POSTGRES_PASSWORD": "AgCrL1g04Qp6M+HtNMskPDXsrj6k24T/0wMIyy3A+qEPIhYuYKrDqQJLZPcgm36AoPPtwEmHZRrqBC/dYRXh25di/72/H5v0wHLohRJiK4Y9GcnA1LpITGPA603YTo9tS3WGKBz1pPj63oLRsdmz4EPj/rgmSSdXcwkakt2M7CV+qCM5e3wYyU8o0576jHKEbjfbYp1EY5jboguyOwBKaIwOXsap3tnQ5dcLY8oyJJh3xlmMdgYdGvgUkSlpMMctVigpCmkTE12M4iIsEe1IlnyhkDdnvnryDjb1MCM94jet6Psr9t9Ou4PZrQm6zdZ2WGFH42mUvzjOYd1ujmzIw7tic+hpBba+sy7xoHkqoBJYjhylGlVSHlgQBc98Q032ye7iqiYCSmeobEnbH8KjYKxPbpZpP+7/jo0tWAv8OFQUZyI8kTib+FXjXPUZyCH/Q+C7vFeIYC+zyF053qnTMy8cNhIz4QTf9r57ePUZ3Dr8a6CPhLkhAw9KqyJB/9TvdoYIKRVBrI8cgGcg7oV1SduKhEyRQIQdBegvk9Dgs/oriJiK9D3vBgXLK/RHJRzd7E9XA5YFSIYSM6dGAJliWDS2b/P1Yo5xoWorZsiayobxDwSK7xA4HGffMkvFe0gEH8xhcxs3nkbzgIGBZsgSjUYdNtVogKcYH0a552bAZ/KMvzR6Wn9SRg+JWzMcwGpo0BD3viml1eG6JPbfgsbEtQbbPg==",
      "POSTGRES_USER": "AgBlhPY55EoRe0iNyohmmwnvV5c2WQ/gZCk/qyUYIUhbWHaj/WPth5MWPumZRaz+WmkZGr6oLZWoKDNGHQUUm0i3A58OOASb2Ygb9Ndyu1/vHrgJggFw76hwkuav3PoDHvKYG/aO/PZYo4a4cbbxSwXV9MxzA4E6vJWcfInOp1Lo58avGpSYiYyzAWmNWFWql7bR15d3fjaPSpJ/jvQhSB27Pf0RYANJvIOmAk6cQTaRTSqtlMmCeN4pWqOgKmZ4F+s84UvkgXYeREOFTgAEWbL/qv2ydtJiLgFdmi9QrmX84+cNYDKXtiaLRjJh57GeYSGFi41+4YyL3xCm0yQpiZC+LCRIQOIWrWTEKCXg6ItmMS8ytaP+l03taEBZwaq++TdXV0fKIioTJGy+Jb7ZsWUDStpRTbGjdqp7i+Hw/R0M7s7iDhAqgRzbqpsjafz/he9gDRwLtDLlkzUnDc2y/AdO+tME6WNA1sYUeyd+8D/PJPgM8jaAD7ACkEFvuwiuhtb48rMiOcOrDCTu1iHbA7cOUYeUVkqwNvCG/LO9gR45aoT7P+bumlxn0zM+cQG3u5p+EzOV2Uf3thl1r1KhNq1D9LhJidgi8f9PzF2kyN0pztKBvj3tRR/D+jsA2Upoi4NaLXkoZ/UwULZmZ3SNKx4WLGOl9NnYakw5D0cQCdJflfm4Hw1/xIMHfXPBijzkQe28RZK7FnIFhhaD"
    }
  }
}
