apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: why-hello
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/joshbrgs/app-why-hello.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
