apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/backstage-namespace.yml
  - base/backstage-sealedsecret.yml
  - base/backstage-svc.yml
  - base/backstage.yml
  - base/postgres-sealedsecret.yml
  - base/postgres-storage.yml
  - base/postgres-svc.yml
  - base/postgres.yml
  - base/an-app-application.yml
  - base/an-app-repo.yml


