name: Build and Push React App Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build React app
        run: yarn build

      - name: Log in to GitHub Container Registry
        run: echo {{ "${{ secrets.GITHUB_TOKEN }}" }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/{{ "${{ github.repository_owner }}" }}/{{cookiecutter.project_slug}}:latest -f Dockerfile .

      - name: Push Docker image
        run: |
          docker push ghcr.io/{{ "${{ github.repository_owner }}" }}/{{cookiecutter.project_slug}}:latest
